# Computational Methods **Lab#1**
## ***Gauss Method** for solving systems of linear equations*

In [1]:
import numpy as np

### About data types and structure of linear systems
* The linear system of equations is set in the form of a matrix equation:
$$
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}\\
\end{pmatrix}
\begin{pmatrix}
x_{1}\\
x_{2}\\
\vdots\\
x_{n}\\
\end{pmatrix}
=
\begin{pmatrix}
b_{1}\\
b_{2}\\
\vdots\\
b_{n}\\
\end{pmatrix}

$$
* The matrix of coefficients is a square matrix of order $n$.

* All elements are of type *float*, except of matrix of coefficients, which is of type *np.float64*.

In [2]:
def swap_first_nonzero(matrix, col, b):
    """
    Swaps the first nonzero element in a column with the first element in the column.

    Parameters
    ----------
    matrix : numpy.ndarray
        The matrix to swap the elements in.
    b : numpy.ndarray
        The vector to swap the elements in.
    col : int
        The column to swap the elements in.

    Returns
    -------
    numpy.ndarray
        The matrix with the elements swapped.
    """
    for i in range(col, len(matrix)):
        if matrix[i][col] != 0:
            matrix[[col, i]] = matrix[[i, col]]
            b[[col, i]] = b[[i, col]]
            return matrix, b

In [3]:
def forward(A, b):
    """
    Converts matrix A into an upper triangular matrix

    Parameters
    ----------
    A : numpy.ndarray
        A square matrix
    b : numpy.ndarray
        A vertical vector
    
    Returns
    -------
    A : numpy.ndarray
        Upper triangular matrix
    """

    A = A.astype(np.float64)
    b = b.astype(float)

    n = len(A)
    for i in range(n-1):
        A, b = swap_first_nonzero(A, i, b)
        for j in range(i+1, n):
            m = A[j][i]/A[i][i]
            A[j] = A[j] - m*A[i]
            b[j] = b[j] - m*b[i]
            
    return A, b


This function computes coefficients of the linear equation system using next formulas:

$$
\large{A_{i} = A_{i} - \frac{a_{ij}}{a_{jj}}A_{j}}
$$

$$
\large{b_{i} = b_{i} - \frac{a_{ij}}{a_{jj}}b_{j}}
$$

where $a_{ij}$ is the coefficient of the linear equation system, $b_{i}$ is the right side of the linear equation system, $A_{i}$ is the matrix of the linear equation system.


In [4]:
#test swap
A = np.array([[0, 1, 2], [0, 4, 5], [6, 7, 8]])
b = np.array([1, 2, 3])
print(swap_first_nonzero(A, 0, b))

(array([[6, 7, 8],
       [0, 4, 5],
       [0, 1, 2]]), array([3, 2, 1]))


In [5]:
#test 1
A = np.array([[0, 4, 2], [0, 5, 3], [2, 3, 3]])
b = np.array([1, 2, 3])

print(forward(A, b))

(array([[ 2. ,  3. ,  3. ],
       [ 0. ,  5. ,  3. ],
       [ 0. ,  0. , -0.4]]), array([ 3. ,  2. , -0.6]))


In [6]:
#test 2
A = np.random.randint(0, 10, (4, 4))
b = np.random.randint(0, 10, (4,))

print(forward(A, b))

(array([[ 7.        ,  1.        ,  2.        ,  3.        ],
       [ 0.        ,  4.42857143,  1.85714286,  1.28571429],
       [ 0.        ,  0.        ,  8.32258065,  3.83870968],
       [ 0.        ,  0.        ,  0.        , -4.20542636]]), array([ 8.        , -4.57142857,  5.12903226,  5.61627907]))


In [7]:
def backward(A_tri, b):
    """
    Solves a system of equations given an upper triangular matrix

    Parameters
    ----------
    A_tri : numpy.ndarray
        A square upper triangular matrix
    b : numpy.ndarray
        A vertical vector
    
    Returns
    -------
    x : numpy.ndarray
        The solution to the system of equations
    """

    n = len(A_tri)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A_tri[i][i+1:], x[i+1:])) / A_tri[i][i]
    return x

This function computes the solution of the linear equation system using next formula:
<br>
$$
\large{x_{i} = \frac{b_{i} - \sum_{j=i+1}^{n}a_{ij}x_{j}}{a_{ii}}}
$$
where $a_{ij}$ is the coefficient of the linear equation system, $b_{i}$ is the right side of the linear equation system, $x_{i}$ is the solution of the linear equation system.



In [8]:
#test 1
A = np.array([[0, 4, 2], [0, 5, 3], [2, 3, 3]])
b = np.array([1, 2, 3])

A_tri, b = forward(A, b)
print(A, b)
print(A_tri, b)
print(backward(A_tri, b))

[[0 4 2]
 [0 5 3]
 [2 3 3]] [ 3.   2.  -0.6]
[[ 2.   3.   3. ]
 [ 0.   5.   3. ]
 [ 0.   0.  -0.4]] [ 3.   2.  -0.6]
[ 6.66133815e-16 -5.00000000e-01  1.50000000e+00]


In [9]:
#test 2
A = np.random.randint(0, 10, (4, 4))
b = np.random.randint(0, 10, (4,))
A_tri, b_new = forward(A, b)
print(A, b)
print(A_tri, b_new)
print(backward(A_tri, b_new))

[[2 8 6 4]
 [4 9 8 7]
 [7 7 5 4]
 [6 1 8 9]] [5 5 6 7]
[[ 2.          8.          6.          4.        ]
 [ 0.         -7.         -4.         -1.        ]
 [ 0.          0.         -4.         -7.        ]
 [ 0.          0.          0.         -5.21428571]] [ 5.         -5.          3.5        11.17857143]
[ 0.65068493 -0.62328767  2.87671233 -2.14383562]


### Final function

In [10]:
def solve(A, b):
    """
    Solves a system of equations given a square matrix

    Parameters
    ----------
    A : numpy.ndarray
        A square matrix
    b : numpy.ndarray
        A vertical vector
    
    Returns
    -------
    x : numpy.ndarray
        The solution to the system of equations
    """

    A_tri, b = forward(A, b)
    return backward(A_tri, b)

In [11]:
solve(A, b)

array([ 0.65068493, -0.62328767,  2.87671233, -2.14383562])